name: Deploy ExpressJS Server to Google Cloud Run

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for google-github-actions/auth@v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_SERVER_DEPLOY_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & Push Docker image
        run: |
          gcloud builds submit backend \
            --tag europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/e-hotel-backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy e-hotel-backend \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/e-hotel-backend:${{ github.sha }} \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated

      - name: Show deployed URL
        run: |
          echo "Backend is live at $(gcloud run services describe e-hotel-backend \
            --region=europe-west1 --format='value(status.url)')"
