name: Deploy Backend to Google Cloud Run

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for google-github-actions/auth@v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          # either via key JSON:
          credentials_json: ${{ secrets.GCP_SA_SERVER_DEPLOY_KEY }}
          # — or via Workload Identity Federation:
          # workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          # service_account: 'github-deploy@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Build & Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: e-hotel-backend
          region: eu-west1
          source: backend
          # <-- drop allow_unauthenticated, use flags instead:
          flags: "--allow-unauthenticated"

      - name: Show deployed URL
        run: |
          echo "✅ Backend is live at ${{ steps.deploy.outputs.url }}"
