name: Deploy ExpressJS Server to Google Cloud Run

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for google-github-actions/auth@v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_SERVER_DEPLOY_KEY }}

      - name: Build & Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: e-hotel-backend
          region: europe-west1
          source: backend
          flags: "--allow-unauthenticated"

      - name: Show deployed URL
        run: |
          echo "Backend is live at ${{ steps.deploy.outputs.url }}"
