name: Deploy Backend to Google Cloud Run

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed by google-github-actions/auth@v1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_SERVER_DEPLOY_KEY }}

      - name: Build container image
        uses: google-github-actions/build@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          path: backend
          dockerfile: backend/Dockerfile
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/e-hotel-backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: e-hotel-backend
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/e-hotel-backend:${{ github.sha }}
          region: eu-west1
          platform: managed
          allow_unauthenticated: true
