name: Build and Deploy ExpressJS Web Server to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_SERVER_DEPLOY_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_LOCATION }}-docker.pkg.dev

      # 🚀 Build and push the image from /backend
      - name: Build and Push Docker image
        run: |
          IMAGE_URI="${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/my-github-action:latest"
          echo "Building Docker image: $IMAGE_URI"
          docker build -t "$IMAGE_URI" ./backend
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy github-cloud-run-service \
            --image "${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/my-github-action:latest" \
            --platform managed \
            --region ${{ secrets.GCP_LOCATION }} \
            --port 8080 \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --service-account ${{ secrets.GCP_SA_SERVER_DEPLOY_NAME }} \
            --allow-unauthenticated
