name: Deploy React App to Firebase Hosting on Merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: React App Env
    steps:
      - uses: actions/checkout@v4

      # Run the install and build commands in the frontend folder
      - name: Install and Build
        run: |
          echo "=== Environment Setup ==="
          echo "Current directory: $(pwd)"
          echo "Environment variables from GitHub:"
          echo "VITE_API_URL=${{ env.VITE_API_URL }}"

          echo "Creating .env file..."
          touch .env
          echo "VITE_API_URL=${{ env.VITE_API_URL }}" > .env

          echo "Contents of .env file:"
          cat .env

          echo "=== Build Process ==="
          echo "Running npm ci..."
          npm ci

          echo "Running npm run build..."
          npm run build

          echo "=== Build Output ==="
          echo "Contents of dist directory:"
          ls -la dist
        working-directory: ./frontend
        env:
          VITE_API_URL: ${{ env.VITE_API_URL }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_E_HOTEL_SDM }}
          channelId: live
          projectId: e-hotel-sdm
          entryPoint: ./frontend
