name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run the install and build commands in the frontend folder
      - name: Install and Build
        run: npm ci && npm run build
        working-directory: ./frontend

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SA_REACTAPP_DEPLOY_KEY }}
          channelId: live
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          entryPoint: ./frontend
